version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: new-ganipedia
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env.production
