version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: new-ganipedia
    ports:
      - "4000:4000"
    restart: always
    env_file:
      - .env.production
    environment:
      - PORT=4000
